@startuml

:Администратор:as A
:Специалисты:as SKS
:Рководители: as RKS


A -up-|> Пользователи
SKS -up-|> Пользователи
RKS-up-|> Пользователи


folder arbor{
:Вход в систему:as (login)


A --> login
RKS --> login
SKS ..> login

folder полномочия_Специалиста_после_входа{

login ..> (Доступно для специалиста): Специалист КС в системе не регистрируется !!!!

}
folder полномочия_Руководителя_после_входа{
login--> (Управление консолью Руководителя)
}
folder полномочия_администратора_после_входа{
login--> (Управление административной консолью)
}
   database DB1 as "arbor
  -------------------
  База содержит информацию о пользователях, процессах
  "

}



@enduml
