@startuml

:Администратор:as A
:Специалисты:as SKS
:Рководители: as RKS


A -up-|> Пользователи
SKS -up-|> Пользователи
RKS-up-|> Пользователи

package Сервер {
package "Веб приложение arbor" as wapp{
(Вход в систему) as login
{
  Login    | "MyName   "
  Password | "****     "
  [Cancel] | [  OK   ]
}

A --> login
RKS --> login
SKS ..>  login




package "Доступно для специалиста" as dds{

login ..> dds: Специалист КС в системе не регистрируется !!!!
(просмотр схем процессов)
(возможность скачивать документацию)
}

package "полномочия Руководителя после входа" as prpin{
login--> prpin
(создание заявок на создание / дороботку процессов)
(отправка заявок в профильнй отдел в отделении)
prpin-->dds
}
package "полномочия администратора после входа" as papin {
login--> papin
(создание / удаление пользователей, назначениние ролей пользователю)-up->(Панель администратора)
(управление ролями)-up->(Панель администратора)
papin-->dds


}




}

package "база данных для веб приложения" as bd{
   database arbor as "arbor
  -------------------
  База содержит информацию о пользователях, процессах
  "
wapp-up->bd
bd-down->wapp
}




wapp-->[web-сервер]
[python3,  flask - webframework]-->[web-сервер]
@enduml
